
- name: Creating a directory for Dockerfile
  file:
    path: /home/joshxh/docker_config
    state: directory

- name: Copying the Dockerfile
  copy:
    remote_src: dockerfile
    dest: /home/joshxh/docker_config
    owner: joshxh
    group: joshxh
  changed_when: false

- name: Creating volume
  file:
    path: /home/joshxh/pages
    state: directory

- name: Building image
  community.docker.docker_image:
    name: lamp-userver
    tag: 1.0
    build:
      path: /home/joshxh/docker_config
    source: build

- name: Deploying container
  community.docker.docker_container:
    name: lamp-userver
    image: lamp-userver:1.0
    state: started
    exposed_ports:
      - "80"
    ports:
      - "8080:80"
    volumes:
      - /home/joshxh/pages:/var/www/html

- block:
  - name: Verify if lamp-userver container is running
    shell: docker ps
    register: container_status

  - debug:
      msg="{{ container_status }}"
